# Generated by Django 4.0.2 on 2022-04-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Employer', 'Employer'), ('Employee', 'Employee')], default='Employee', max_length=30),
        ),
    ]
