# Generated by Django 4.0.2 on 2022-05-11 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_profile_user_associated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
