# Generated by Django 4.0.2 on 2022-04-15 11:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_profile_allergies_alter_profile_designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certification',
            name='cert_image',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='certification',
            name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='certification',
        ),
        migrations.AddField(
            model_name='certification',
            name='name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserUploadedCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_image', models.ImageField(upload_to='Certification/')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('cert_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.certification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
