# Generated by Django 4.0.2 on 2022-04-18 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_remove_certification_cert_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useruploadedcertificate',
            options={'verbose_name': 'UserUploadedCertificate'},
        ),
        migrations.AlterField(
            model_name='profile',
            name='allergies',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='designation',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='medical_issues',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, upload_to='Profile/'),
        ),
    ]
