# Generated by Django 4.0.2 on 2022-04-18 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_useruploadedcertificate_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='profile_img',
            new_name='profile_image',
        ),
    ]
