# Generated by Django 4.0.2 on 2022-04-18 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='answer',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.TextField(default=''),
        ),
    ]
