# Generated by Django 4.0.2 on 2022-04-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_faq_answer_alter_faq_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='question',
            field=models.CharField(default='', max_length=250),
        ),
    ]
