# Generated by Django 4.0.2 on 2022-04-21 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='job',
            new_name='job_assigned',
        ),
    ]
