# Generated by Django 4.0.2 on 2022-04-15 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
