# Generated by Django 4.0.2 on 2022-04-15 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_assigned', '0001_initial'),
        ('notes', '0002_alter_notes_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='job_assigned.jobassigned'),
        ),
    ]
