# Generated by Django 4.0.2 on 2022-04-27 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_assigned', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassigned',
            name='duration_worked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobassigned',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobassigned',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
