# Generated by Django 4.0.2 on 2022-04-27 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("job_assigned", "0006_alter_working_duration_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="working_duration",
            name="duration",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
