# Generated by Django 4.0.2 on 2022-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_assigned', '0008_working_duration_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='working_duration',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
