# Generated by Django 4.0.2 on 2022-04-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_assigned", "0005_working_duration_timestamp_and_more"),
        ("job_assigned", "0009_alter_working_duration_duration"),
    ]

    operations = []
