# Generated by Django 4.0.2 on 2022-04-29 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("job_assigned", "0010_merge_20220428_1709"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Working_Duration",
            new_name="WorkingDuration",
        ),
    ]
