# Generated by Django 4.0.2 on 2022-05-13 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_assigned', '0011_rename_working_duration_workingduration'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobassigned',
            name='assgned_status',
            field=models.BooleanField(default=True),
        ),
    ]
