# Generated by Django 4.0.2 on 2022-05-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_assigned', '0012_jobassigned_assgned_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobassigned',
            old_name='assgned_status',
            new_name='assigned_status',
        ),
    ]
