# Generated by Django 4.0.2 on 2022-04-14 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ('timestamp',), 'verbose_name': 'Job'},
        ),
    ]
