# Generated by Django 4.0.2 on 2022-04-14 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_alter_job_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='worked_hours',
        ),
    ]
